slice_name: Boy Name Cloud
description: null
certified_by: null
certification_details: null
viz_type: word_cloud
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '100'
  markup_type: markdown
  metric: sum__num
  rotation: square
  row_limit: 50000
  series: name
  size_from: '10'
  size_to: '70'
  time_range: '100 years ago : now'
  viz_type: word_cloud
query_context: null
cache_timeout: null
uuid: 1fa276d6-9d83-48c0-b30a-8457a8ca49d6
version: 1.0.0
dataset_uuid: b634c33a-442c-4f5c-a715-c808b60d2d94
