slice_name: Boys
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50
  time_range: '100 years ago : now'
  timeseries_limit_metric: sum__num
  viz_type: table
query_context: null
cache_timeout: null
uuid: 6d5f0b1a-4ed5-4c6e-9973-065316bdccc0
version: 1.0.0
dataset_uuid: b634c33a-442c-4f5c-a715-c808b60d2d94
