slice_name: Pivot Table v2
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  groupbyColumns:
  - state
  groupbyRows:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: pivot_table_v2
query_context: "{\"datasource\": {\"id\": 4, \"type\": \"table\"}, \"queries\": [{\"columns\": [\"name\", \"state\"], \"metrics\": [\"sum__num\"]}], \"result_format\": \"json\", \"result_type\": \"full\"}"
cache_timeout: null
cache_timeout: null
uuid: f2b96009-3026-45ce-85af-13b7d5914709
version: 1.0.0
dataset_uuid: b634c33a-442c-4f5c-a715-c808b60d2d94
